// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversalCarShop.Infrastructure.Database;

#nullable disable

namespace UniversalCarShop.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250401220040_initial migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("UniversalCarShop.Infrastructure.Database.CarEntity", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Number");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("UniversalCarShop.Infrastructure.Database.CustomerEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CarNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HandPower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LegPower")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.HasIndex("CarNumber")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("UniversalCarShop.Infrastructure.Database.CustomerEntity", b =>
                {
                    b.HasOne("UniversalCarShop.Infrastructure.Database.CarEntity", "Car")
                        .WithOne()
                        .HasForeignKey("UniversalCarShop.Infrastructure.Database.CustomerEntity", "CarNumber");

                    b.Navigation("Car");
                });
#pragma warning restore 612, 618
        }
    }
}
