version: '3'
services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: car-shop-db-pass
      POSTGRES_DB: car-shop-db
      POSTGRES_USER: car-shop-db
  universal-car-shop:
    image: universal-car-shop
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      CONNECTIONSTRINGS__PostgreSQL: Host=postgres;Database=car-shop-db;Username=car-shop-db;Password=car-shop-db-pass
      ASPNETCORE_ENVIRONMENT: Development
